<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/Bush.glb --shadows --types
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Object_6: THREE.Mesh
      Object_8: THREE.Mesh
      Object_10: THREE.Mesh
      Object_12: THREE.Mesh
      Object_14: THREE.Mesh
      Object_16: THREE.Mesh
      Object_18: THREE.Mesh
      Object_20: THREE.Mesh
      Object_22: THREE.Mesh
      Object_24: THREE.Mesh
      Object_28: THREE.Mesh
      Object_30: THREE.Mesh
      Object_32: THREE.Mesh
      Object_34: THREE.Mesh
      Object_36: THREE.Mesh
      Object_38: THREE.Mesh
      Object_40: THREE.Mesh
      Object_42: THREE.Mesh
      Object_4: THREE.Mesh
      Object_26: THREE.Mesh
    }
    materials: {
      ['Material.004']: THREE.MeshStandardMaterial
      material_0: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Bush.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[0, 0.13, 0.33]}
      rotation={[-Math.PI / 2, 0, 0.41]}
      scale={0.12}
    >
      <T.Group rotation={[Math.PI / 2, 0, 0]}>
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_6.geometry}
          material={gltf.materials['Material.004']}
          position={[0, 3.05, -1.02]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_8.geometry}
          material={gltf.materials['Material.004']}
          position={[-2.45, 2.43, 0]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_10.geometry}
          material={gltf.materials['Material.004']}
          position={[2.84, 2.3, 0]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_12.geometry}
          material={gltf.materials['Material.004']}
          position={[-0.44, 2.42, 2.72]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_14.geometry}
          material={gltf.materials['Material.004']}
          position={[1.35, 2.06, -4.98]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_16.geometry}
          material={gltf.materials['Material.004']}
          position={[-2.89, 0.64, 0]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_18.geometry}
          material={gltf.materials['Material.004']}
          position={[-2.23, 0.64, -2.77]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_20.geometry}
          material={gltf.materials['Material.004']}
          position={[2.69, 0.64, -2.77]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_22.geometry}
          material={gltf.materials['Material.004']}
          position={[2.69, 0.64, 1.32]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_24.geometry}
          material={gltf.materials['Material.004']}
          position={[-2.08, 0.64, 2.37]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_28.geometry}
          material={gltf.materials['Material.004']}
          position={[2.43, 0.67, -6.44]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_30.geometry}
          material={gltf.materials['Material.004']}
          position={[-1.29, 2.05, -5.84]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_32.geometry}
          material={gltf.materials['Material.004']}
          position={[-1.2, 0.77, -7.33]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_34.geometry}
          material={gltf.materials['Material.004']}
          position={[0.77, 0.56, 3.34]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_36.geometry}
          material={gltf.materials['Material.004']}
          position={[1.7, 0.83, -7.94]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_38.geometry}
          material={gltf.materials['Material.004']}
          position={[-2.54, 0.87, -4.33]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_40.geometry}
          material={gltf.materials.material_0}
          position={[0.59, 1.35, -6.82]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_42.geometry}
          material={gltf.materials['Material.004']}
          position={[1.9, 1.87, -2.57]}
          scale={0.28}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_4.geometry}
          material={gltf.materials['Material.002']}
          scale={2.98}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Object_26.geometry}
          material={gltf.materials['Material.001']}
          position={[0, -0.13, -5.42]}
          scale={2.77}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
