<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/Tree.glb --shadows --types
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh
      Icosphere: THREE.Mesh
      Icosphere001: THREE.Mesh
      Icosphere002: THREE.Mesh
      Icosphere003: THREE.Mesh
      Icosphere004: THREE.Mesh
      Icosphere005: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      ['Material.001']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      ['Material.003']: THREE.MeshStandardMaterial
      ['Material.004']: THREE.MeshStandardMaterial
      ['Material.005']: THREE.MeshStandardMaterial
      ['Material.006']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Tree.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials.Material}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Icosphere.geometry}
      material={gltf.materials['Material.001']}
      position={[-0.99, 2.31, 0.71]}
      scale={[0.72, 0.44, 0.6]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Icosphere001.geometry}
      material={gltf.materials['Material.002']}
      position={[0.76, 3.1, 0.86]}
      rotation={[0.32, 0.82, 0.53]}
      scale={0.6}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Icosphere002.geometry}
      material={gltf.materials['Material.003']}
      position={[0.09, 1.99, -0.85]}
      rotation={[0.15, 0.53, -0.5]}
      scale={[0.57, 0.46, 0.54]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Icosphere003.geometry}
      material={gltf.materials['Material.004']}
      position={[-1.25, 3.05, -0.43]}
      rotation={[0.1, 0.62, 0.67]}
      scale={[0.62, 0.66, 0.51]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Icosphere004.geometry}
      material={gltf.materials['Material.005']}
      position={[0.31, 3.04, -0.1]}
      rotation={[2.97, 1.22, -2.85]}
      scale={[0.53, 0.33, 0.63]}
    />
    <T.Mesh
      castShadow
      receiveShadow
      geometry={gltf.nodes.Icosphere005.geometry}
      material={gltf.materials['Material.006']}
      position={[0.85, 2.83, -0.97]}
      rotation={[0, 0, -0.51]}
      scale={[0.66, 0.66, 0.57]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
