<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/Flowers.glb --draco --types
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Circle001_Material001_0: THREE.Mesh
      Circle006_Circle007_Material001_0: THREE.Mesh
    }
    materials: {
      ['Material.001']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Flowers.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[0.17, 0.94, -0.58]}
      rotation={[-Math.PI / 2, 0, -0.74]}
      scale={0.05}
    >
      <T.Group rotation={[Math.PI / 2, 0, 0]}>
        <T.Mesh
          geometry={gltf.nodes.Circle001_Material001_0.geometry}
          material={gltf.materials['Material.001']}
          position={[19.36, 21.39, 11.67]}
          scale={100}
        />
        <T.Mesh
          geometry={gltf.nodes.Circle006_Circle007_Material001_0.geometry}
          material={gltf.materials['Material.001']}
          position={[-12.33, 25.21, 6.35]}
          scale={100}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
